### ISSUE TITLE
Change Output Directory Issue

### ISSUE THREAD

**Issue by bridgeri127** [andrewzach/Blackboard-Downloader#12]
Hi Andrew

Slight issue I've found testing your downloader, when you change the output directory, if the user does not end the directory path with a '\', you ended up with an oddly concatenated directory name rather than sub directories. Should be fixed by simply checking for a '/' at the end of the directory path and appending it if it is not there!

**Comment by andrewzach** [comment]
Fixed! It now adds a \ to the end if not already present.
